language: python

python:
  - "3.5"
  - "3.6"

before_install: "pip install tox-travis"
install: "python setup.py install"
before_script: "flake8 --ignore=E501 loafer"
script: "tox"
after_success: coveralls
